---
  - name: Ansible Playbook
    hosts: localhost
    connection: local
    gather_facts: false
    tasks:
      - name: Add role 
        ansible.builtin.include_role:
          name: vc_nsx_tags_comparison_final